RADIOLOGIE_INTERVENTIONNELLE_CARDIOLOGIE = r"I:\Radiophysique-Radioprotection\Radiophysique\Dosimétrie patient\Suivi dose cardio int\DATA\Cardio int global.xlsx"
RADIOLOGIE_INTERVENTIONNELLE_NEURORADIOLOGIE_VASCULAIRE = r"I:\Radiophysique-Radioprotection\Radiophysique\Dosimétrie patient\Suivi dose installations fixes\DATA"
SCANNERS = r"I:\Radiophysique-Radioprotection\Radiophysique\Dosimétrie patient\Suivi dose scanners\scanners global.xlsx"
RADIOLOGIE_CONVENTIONNELLE = r"I:\Radiophysique-Radioprotection\Radiophysique\Dosimétrie patient\Suivi de dose salles conventionnelles\conventionnel_global.xlsx"
MAMMOGRAPHIE = r"I:\Radiophysique-Radioprotection\Radiophysique\Dosimétrie patient\Suivi de dose salles conventionnelles\conventionnel_global.xlsx"
RADIOLOGIE_DENTAIRE = r""
BLOC_OPERATOIRE = r"I:\Radiophysique-Radioprotection\Radiophysique\Dosimétrie patient\Suivi dose BO\DATA\GLOBAL\global V2.xlsx"
MEDECINE_NUCEAIRE = r""

CSV_RADIOLOGIE_INTERVENTIONNELLE_CARDIOLOGIE = r"C:\Users\BACHELEN\Documents\PROJECTS\dosimetric_data_analysis\data\radiologie_interventionnelle_cardiologie.csv"
CSV_RADIOLOGIE_INTERVENTIONNELLE_NEURORADIOLOGIE_VASCULAIRE = r"C:\Users\BACHELEN\Documents\PROJECTS\dosimetric_data_analysis\data\cardiologie_interventionnelle_neurologie_vasculaire.csv"
CSV_SCANNERS = r"C:\Users\BACHELEN\Documents\PROJECTS\dosimetric_data_analysis\data\scanners.csv"
CSV_RADIOLOGIE_CONVENTIONNELLE = r"C:\Users\BACHELEN\Documents\PROJECTS\dosimetric_data_analysis\data\radiologie_conventionnelle.csv"
CSV_MAMMOGRAPHIE = r"C:\Users\BACHELEN\Documents\PROJECTS\dosimetric_data_analysis\data\mammographie.csv"
CSV_RADIOLOGIE_DENTAIRE = r"C:\Users\BACHELEN\Documents\PROJECTS\dosimetric_data_analysis\data\radiologie_dentaire.csv"
CSV_BLOC_OPERATOIRE = r"C:\Users\BACHELEN\Documents\PROJECTS\dosimetric_data_analysis\data\bloc_operatoire.csv"
CSV_MEDECINE_NUCEAIRE = r"C:\Users\BACHELEN\Documents\PROJECTS\dosimetric_data_analysis\data\medecine_nucleaire.csv"

